name = "poristiwa-aggregator"
main = "src/workers/aggregator.js"
compatibility_date = "2026-03-08"

[ai]
binding = "AI" # This allows the 'env.AI' call to work

[[d1_databases]]
binding = "DB"
database_name = "poristiwa-db"
database_id = "49fc255a-c312-4853-b290-ead3e4c3490b"

[vars]
SITE_URL = "https://poristiwa.my.id"
INDEXNOW_KEY = "poristiwa1234567890abcdefghijk"

[triggers]
crons = ["*/30 * * * *"]
